version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: mukit_db
      POSTGRES_USER: mukit_user
      POSTGRES_PASSWORD: mukit_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U mukit_user -d mukit_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
    environment:
      DATABASE_URL: postgresql+asyncpg://mukit_user:mukit_password@db:5432/mukit_db
      REDIS_URL: redis://redis:6379/0
      SECRET_KEY: your-secret-key-change-in-production
      ALLOWED_ORIGINS: http://localhost:3333,http://localhost:5173
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - ./uploads:/app/uploads
    command: >
      sh -c "
        alembic upgrade head &&
        uvicorn main:app --host 0.0.0.0 --port 8888 --reload
      "

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3333:3333"
    environment:
      VITE_API_URL: http://localhost:8888/api/v1
      VITE_WS_URL: ws://localhost:8888
    depends_on:
      - backend
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public

volumes:
  postgres_data:
  redis_data:

